/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package project;
import java.awt.print.PrinterException;
import java.sql.*;
import java.text.MessageFormat;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import static project.globalvariable.PASSWORD;
import static project.globalvariable.PATH;
import static project.globalvariable.PLACE;
import static project.globalvariable.USERNAME;
/**
 *
 * @author shagu
 */
public class participantlist extends javax.swing.JInternalFrame implements globalvariable {

    /** Creates new form eventlist */
    public participantlist() {
        initComponents();
        Connection myconnection;
        
        try {//for connection.
            myconnection=DriverManager.getConnection(PATH+PLACE, USERNAME, PASSWORD);//if coonection is not made error should be handled so use try and catch
            try//for query.
            {
                String a="select * from event_type";//fetch all from that table.
                PreparedStatement mystatement =myconnection.prepareStatement(a);
                ResultSet myresult=mystatement.executeQuery();
                
                if(myresult.next())//returns 0 if not able to execute query
                {
                    //first time condition is checked so do-while.
                    do
                    {
                        eventtypebox.addItem(myresult.getString("eventtype"));
                }while(myresult.next());//second time condition checked.
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "No Event Type Added");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
            }
            finally
            {
                myconnection.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error in Connection"+e.getMessage());
            
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eventtypebox = new javax.swing.JComboBox<>();
        eventbox = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Participants List");

        eventtypebox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Event Type" }));
        eventtypebox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventtypeboxActionPerformed(evt);
            }
        });

        eventbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Event" }));
        eventbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventboxActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "College", "Student ID", "Mobile Number", "Email"
            }
        ));
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(eventtypebox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81)
                .addComponent(eventbox, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addComponent(jButton1)
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eventtypebox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eventbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eventtypeboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventtypeboxActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
        if(eventtypebox.getSelectedIndex()>0)//then only events should appear.
        {
            Connection myconnection;

            try {//for connection.
                myconnection=DriverManager.getConnection(PATH+PLACE, USERNAME, PASSWORD);//if coonection is not made error should be handled so use try and catch
                try//for query.
                {
                    String a="select * from event_detail where etype=?";//column fetch according to event type.//particular event of that eventtype should come.
                    PreparedStatement mystatement =myconnection.prepareStatement(a);
                    mystatement.setString(1,eventtypebox.getSelectedItem().toString());
                    ResultSet myresult=mystatement.executeQuery();

                    if(myresult.next())//returns 0 if no event of that type exist.
                    {
                        eventbox.removeAllItems();
                        eventbox.addItem("Select Event");
                        do
                        {
                            eventbox.addItem(myresult.getString("ename"));//get value from the ename column in the database.
                        }while(myresult.next());//second time condition checked.
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "No Event Added ");
                        eventbox.removeAllItems();
                        eventbox.addItem("Select Event");
                    }
                }
                catch(Exception e){
                    JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
                }
                finally
                {
                    myconnection.close();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane,"Error in Connection"+e.getMessage());

            }
        }
        else 
        {
            eventbox.removeAllItems();
            eventbox.addItem("Select Event");
            mymodel.setRowCount(0);
        }
    }//GEN-LAST:event_eventtypeboxActionPerformed

    private void eventboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventboxActionPerformed
        // TODO add your handling code here:
        if(eventbox.getSelectedIndex()>0)
        {
            Connection myconnection;
        
        try {//for connection.
            myconnection=DriverManager.getConnection(PATH+PLACE, USERNAME, PASSWORD);//if coonection is not made error should be handled so use try and catch
            try//for query.
            {
                String a="select * from participant_record,event_register where participant_record.pid=event_register.id and eventname=?";//fetch all from that table.
                PreparedStatement mystatement =myconnection.prepareStatement(a);
                mystatement.setString(1,eventbox.getSelectedItem().toString());
                DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
                ResultSet myresult=mystatement.executeQuery();
                
                if(myresult.next())//returns 0 if not able to execute query
                {
                    //first time condition is checked so do-while.
                    mymodel.setRowCount(0);
                    do
                    {
                        //we are getting it and putting it into variables.
                        String  pname,pcollege,pid,pmobile,pemail;
                        pname=myresult.getString("pname");
                        pcollege=myresult.getString("pcollege");
                        pid=myresult.getString("pid");//we have to set string in the table.
                        pmobile=myresult.getString("pmobile");
                        pemail=myresult.getString("pemail");
                        mymodel.addRow(new Object[]{pname,pcollege,pid,pmobile,pemail});
                      //it is in loop first row first array,for every row new array is made.
                        
                }while(myresult.next());//second time condition checked.
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "No Event Type Added");
                }
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error in query " + e.getMessage());
            }
            finally
            {
                myconnection.close();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane,"Error in Connection"+e.getMessage());
            
        }
        }
    }//GEN-LAST:event_eventboxActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         MessageFormat myheader=new MessageFormat(eventbox.getSelectedItem().toString());
        MessageFormat myfooter=new MessageFormat("Page{0}");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, myheader, myfooter);
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(rootPane,"Error in Printing");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> eventbox;
    private javax.swing.JComboBox<String> eventtypebox;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

}
